# -*- coding: utf-8 -*-
"""HACKING TOOLS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PM1UrAYFtIHOb-CsEdE5_8Vlc1PEyk6C
"""

#3.1.1. NMAP - Ejemplo de Código en Python (para fines educativos):

import nmap

def escanear_puertos(ip):
    nm = nmap.PortScanner()
    nm.scan(ip, arguments='-p 1-1000')

    for host in nm.all_hosts():
        print(f'Estado de {host}: {nm[host].state()}')
        for proto in nm[host].all_protocols():
            print(f'Protocolo : {proto}')

            lport = nm[host][proto].keys()
            for port in lport:
                print(f'Puerto {port}: Estado {nm[host][proto][port]["state"]}')

# Ejecutar el escaneo
escanear_puertos('192.168.1.1')

#Explicación:
#Este código utiliza la biblioteca Nmap para Python para realizar un escaneo de puertos en la dirección IP 192.168.1.1,
# mostrando el estado de los puertos y protocolos.

#5.1.2. NetCat - Ejemplo de Código en Bash (para fines educativos):

# Crear un servidor de escucha en el puerto 8080
nc -lvp 8080

# Conectar al servidor desde otro terminal
nc 127.0.0.1 8080

#Explicación:
#Este código utiliza NetCat para crear un servidor de escucha en el puerto 8080 y luego se conecta al servidor desde otra terminal.

#5.2.1. TCP Dump / Wireshark - Ejemplo de Código en Bash (para fines educativos):

# Capturar tráfico en el adaptador eth0 y guardarlo en un archivo
tcpdump -i eth0 -w captura.pcap

#Explicación:
#Este comando utiliza TCP Dump para capturar el tráfico en el adaptador de red eth0 y guardarlo en un archivo llamado captura.pcap.

#5.6. Herramientas de Cifrado - Ejemplo de Cifrado con GPG en Python (para fines educativos):

import os
import gnupg

def cifrar_archivo(archivo, destinatario):
    gpg = gnupg.GPG()
    with open(archivo, 'rb') as f:
        cifrado = gpg.encrypt_file(f, destinatario, output=f'{archivo}.gpg')
    print(f'Archivo cifrado: {cifrado}')

# Ejemplo de uso
cifrar_archivo('documento.txt', 'destinatario@example.com')

#Explicación:
#Este código utiliza la biblioteca gnupg para Python y cifra el contenido del archivo 'documento.txt'
#utilizando GPG, generando un archivo cifrado con la extensión .gpg.